version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
  # backend:
  #   container_name: app_backend
  #   build: ./back-end
  #   ports:
  #     - 8081:80
  #   depends_on:
  #     db:
  #       condition: service_started
  frontend:
    container_name: app_frontend
    build: ./front-end
    ports:
      - 8080:8080
    platform: linux/x86_64
    working_dir: /app-frontend
    # depends_on:
    #   backend:
    #     condition: service_started
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 5s
      retries: 3

networks:
  default:
    name: accenture_test