version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"
  # backend:
  #   container_name: app_backend
  #   build: ./back-end
  #   ports:
  #     - 3001:3001
  #   platform: linux/x86_64
  #   working_dir: /app-backend
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     - APP_PORT=3001
  #     - DB_USER=root
  #     - DB_PASS=123456
  #     - DB_HOST=db
  #     - DB_PORT=3306
  #   healthcheck:
  #     test: ["CMD", "lsof", "-t", "-i:3001"]
  #     timeout: 5s
  #     retries: 3
  frontend:
    container_name: app_frontend
    build: ./front-end
    ports:
      - 8080:8080
    platform: linux/x86_64
    working_dir: /app-frontend
    # depends_on:
    #   backend:
    #     condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"]
      timeout: 5s
      retries: 3

networks:
  default:
    name: accenture_test